### ISSUE TITLE
[Request] Make LED ring optional

### ISSUE THREAD

**Issue by denniedegroot** [PandaNL/nl.tonversteeg.pushover#1]
Could the LED ring color (green / red) confirmation of sending a message be made optional?
Maybe a setting on the settings page? I currently use Pushover and a LED Ring action together and it looks weird when pushover makes it green :)

**Comment by PandaNL** [comment]
Sure thing Dennie, version 0.0.3 is just submitted and waiting for approval so will implement this in version 0.0.4.

Thank you for your request.

**Comment by denniedegroot** [comment]
Awesome!

**Comment by PandaNL** [comment]
Checkbox to disable ledring is implemented and will be in Version 0.0.5
