### ISSUE TITLE
Add reboot homey instruction to manual

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [PandaNL/nl.tonversteeg.pushover#13]
Installed Pushover and followed instructions, but only on forum I found that I need to reboot the Homey to get it work.

Please add the reboot instruction to the instructions on the page of apps.athom.com and on the first forum page.

**Comment by Veldkornet** [comment]
I don’t see why you would need to reboot Homey to make the app work. 

If you needed to do this, I suspect that it was environment specific.
