### ISSUE TITLE
I cannot use the tag for the photo sending

### ISSUE THREAD

**Issue by RaimondB** [PandaNL/nl.tonversteeg.pushover#16]
In the flow editor I try to drag and drop, but the imagetoken tag will not drop on the tag icon.
I'm using the 0.0.9 version and using the synology trigger card that reacts to an camera snaphot becoming available. 
Is there any way to provide some logging so you will be able to check what is going wrong?

**Comment by ketra** [comment]
sorry linked the wrong commit here, as i can recall this is an issue within the flow editor of athom. you can try the homey app or a different browser, i had the same problem couple of times the image token is quite buggy

**Comment by Veldkornet** [comment]
Is this issue still relevant?

**Comment by RaimondB** [comment]
For me personally not anymore since i am now using a different messaging
service

Op di 28 mei 2019 19:14 schreef Veldkornet <notifications@github.com>:

**Comment by PandaNL** [comment]
As of v0.0.10 using a image tag works.
