### ISSUE TITLE
Homey: Pushover Android app without settings for user key?

### ISSUE THREAD

**Issue by dreamerbb** [PandaNL/nl.tonversteeg.pushover#19]
Hi community, 

I recently upgraded my Homey to the latest version and cannot use the Web GUI anymore. Since then, my Pushovers aren´t working anymore, I can´t even find the settings where I can insert my user ID and my token. Can you please help? 

Best regards,
db

**Comment by tacta** [comment]
This is the same for IOS.

**Comment by PandaNL** [comment]
Just set the beta to stable, please update and try again.

For IOS (don't know about Android) go to More > Settings > Pushover Notifications
