### ISSUE TITLE
does not work after upgrade to Homey 2

### ISSUE THREAD

**Issue by WimHe** [PandaNL/nl.tonversteeg.pushover#20]
After upgrading to Homey 2 my flows don't work and cannot set email address for push messages.
When testing a flow an error message appears briefly, too short to be useful.

**Comment by tacta** [comment]
Indeed it stopt werking after the Homey update. The solution for me was to unistall pushover and install the beta version V 0.10. 
This beta version has the option for the License key. It even remembered the key from the previous version.

**Comment by PandaNL** [comment]
Hello,

I set the beta version as stable, please update the app and try again.

For IOS (don't know about Android) go to More > Settings > Pushover Notifications

**Comment by Joozt** [comment]
It is nice that with the auto update it automatically started working again.

Only issue now is that the message priorities are not passed. All messages have "normal" priority.
