### ISSUE TITLE
Pushover app not working since today

### ISSUE THREAD

**Issue by Marcel-van-Beuzekom** [PandaNL/nl.tonversteeg.pushover#28]
Starting today the pushover app is crashing. Restarting the app or restarting Homey is not helping. This is my error report:

https://photos.app.goo.gl/89xvxMSwphsYQyK27

**Comment by wfdekker** [comment]
Yes I have this same issue, after the update a few saus ago the app crashes after restart or reboot of Homey :-(

**Comment by pulsebreaker** [comment]
Same here. Restarting the app seems to help until the app has to send a Pushover message, it will crash right away.

**Comment by Marcel-van-Beuzekom** [comment]
I have removed the app and replaced it with the "http request" app, by Erik van Dongen. With this app you can post do the post yourself in the flow. Works like a charm

https://i.imgur.com/UDQHs0c.png

**Comment by PandaNL** [comment]
Hello,

I pushed update 0.0.13 as beta, but accidentally published the beta as stable.

I contacted Athom to set it back to stable version 0.0.10 but they told me this was not possible.

I will try to fix this asap.

Thank you for your patience.

**Comment by pulsebreaker** [comment]
I managed to get it to work again. New flowcards huh? Nice.

Not sure what did the trick. I reinstalled the app on Homey, after that I
saw there are new cards with new fields for Pushover. I filled them with a
0 and it worked.

regards,


Op vr 12 jul. 2019 om 10:28 schreef Ton Versteeg <notifications@github.com>:

**Comment by PandaNL** [comment]
Yes, I think a reinstall does it.

I removed the app and uploaded it via the CLI to debug it, but I'm not able yet to get the app to crash.

**Comment by PandaNL** [comment]
Please update your current Pushover flowcards, and fill in the emergency retry interval and the Emergency Retry Expiration, set them to 0 if you don't want to use those features. This should fix it. 

Otherwise do a uninstall and re-install.

**Comment by casper181** [comment]
Done uninstall but still having issues

**Comment by PandaNL** [comment]
Did you edit every flow with the pushover card to fill in the missing parameters?

**Comment by wfdekker** [comment]
It was a lot of work but modifying all cards and adding a name and setting the 2 parameters to 0 fixed it. Glad to be getting messages again.
