### ISSUE TITLE
[Feature Request] Support Sending Images

### ISSUE THREAD

**Issue by Veldkornet** [PandaNL/nl.tonversteeg.pushover#4]
Could you please support the sending of images with the [Image Grabber](https://github.com/jordenc/image.grabber) app?

**Comment by rwilleme** [comment]
As a workaround, you can also use the Email Gateway to get this working:
https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30

However, this takes more time to get processed.
In my case, where I use it for my doorbell, the people already left before I got the camera image on my Apple Watch. :sweat_smile:

**Comment by Veldkornet** [comment]
Apparently I was ahead of my time :P
https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30

But now that it’s supported, can we have it added?
Generic Image tokens have also been added to Homey since then.

**Comment by Veldkornet** [comment]
FYI, PushSafer, which is a fork of this, already has everything implemented: https://github.com/appzer/Athom-Homey-Pushsafer

**Comment by PandaNL** [comment]
Kevin Traa has created a module for image grabbing, In the process of merging his code with mine and need to do some testing. After this is done the app will be updated.

**Comment by Veldkornet** [comment]
Looking forward to it

**Comment by marcschut002** [comment]
any update on this? 0.0.9 is not available yet @ Homey Apps

**Comment by PandaNL** [comment]
0.0.9 beta is submitted, and is waiting for aproval from Athom.

**Comment by marcschut002** [comment]
Thanks! I will check it out as soon as it's approved.

**Comment by PandaNL** [comment]
0.0.9 is now available as beta, please let me know if you find any issues.

**Comment by Veldkornet** [comment]
Seems to work okay for me using the ImageGrabber app. No issues from a Pushover side.
You're forced to add text, but that's just how Homey works. All fields are mandatory.

Although unfortunately, not related to Pushover, ImageGrabber is dead slow in actually grabbing the image...

**Comment by marcschut002** [comment]
I have also tested it with ImageGrabber (can't seem to get the snapshot trigger from synology working but ok), but I always get the Homey Image as push message. Not the image from the url I tested with ImageGrabber. Any idea why?

**Comment by Veldkornet** [comment]
ImageGrabber, or the image token itself is buggy. Check that you're using the image token with the small "i" if you have more than one. So " image", not "Image".
Secondly, the "Test Flow" always sends me the homey Image as well regardless of what URL I use. IF you want to really test it you have to actually trigger the flow.

Ie, just make a flow that says, when this flow is triggered, grab this image. And then execute that flow.

**Comment by marcschut002** [comment]
It's working! This time I didn't use the Test Flow option. Thanks for this release!

**Comment by PandaNL** [comment]
Update should be live now as beta

**Comment by Veldkornet** [comment]
I guess we can close this :)
