### ISSUE TITLE
Homey Pro 2023 Support for Pushover Notifications

### ISSUE THREAD

**Issue by lillevikh** [PandaNL/nl.tonversteeg.pushover#40]
Hi,
Forst of all - thanks for your effort and all the work done!

Any chance of support for the Homey Pro 2023 on the Pushover Notifications any time soon?

Brgds
Håvard

**Comment by W-illi4m** [comment]
+1 Please support new homey pro 2023!
I'm waiting for an operational version.
Thanks!

**Comment by advanliempt** [comment]
i'm waiting to

**Comment by ulfmodig** [comment]
I used this on my old Homey. It would be very nice to use it on 2023 as well. I hope for an upgrade...

**Comment by PandaNL** [comment]
Please see https://github.com/PandaNL/nl.tonversteeg.pushover/issues/35 for current test version.
