### ISSUE TITLE
Emergency Priority

### ISSUE THREAD

**Issue by MarkvandenBroek** [PandaNL/nl.tonversteeg.pushover#6]
It would be a great feature if a user could enable '[Emergency Priority](https://pushover.net/api#priority)' in a Homey Flow and set 'Retry' and 'Expire' parameters in every flow. Homey sucks big time in 'alarming' users when something is wrong: e.g. when smoke is detected or a door is opened. All push messages Homey delivers are the same, so there's no way to distinguish between the 'life-saving' or 'life threatening' ones and the normal push messages. Pushover provides an 'Emergency Priority' message profile to warn users - repeatedly, until the message is dismissed - of such situations. Your Homey-app could fill this void in the native Homey functionality.

**Comment by PandaNL** [comment]
WIll add this soon.

**Comment by rwilleme** [comment]
Any progress on this feature request?

**Comment by Veldkornet** [comment]
I think that this relates to #21

**Comment by Veldkornet** [comment]
I've put in a pull request to put in all of the relevant parameters etc which will fix this issue.
Although ultimately #21 will need to be fixed as well before it will actually work as intended.
